version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Crear entorno virtual
          command: python -m venv venv
      - run:
          name: Instalar dependencias
          command: |
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Verificar entorno funcionando
          command: |
            . venv/bin/activate
            echo "Entorno listo. Sin pruebas por ahora."

workflows:
  version: 2
  build-workflow:
    jobs:
      - build

